### ISSUE TITLE
Installation on 3.5.2

### ISSUE THREAD

**Issue by johnpap21** [cnw-co/moodle-local_cnw_smartcohort#1]
Hello

I am trying to install this on a site that is 3.5.2, but it comes up with the version of Moodle is incorrect.  Can you please help?

TIA
JP

**Comment by cnw-co** [comment]
Hello!

Thanks for you reply. The plugin's minimum Moodle version is 3.5.4 but we just tested it on 3.5.0 and everything seems good, so we created a new release. 

Please check it out and report back to us.

Thanks,
CNW Co.

**Comment by johnpap21** [comment]
Worked thank you very much 👍

**Comment by cnw-co** [comment]
You'r welcome!
