### ISSUE TITLE
SQL error on a Postgre SQL database

### ISSUE THREAD

**Issue by bradnielsen2981** [cnw-co/moodle-local_cnw_smartcohort#2]
Hi, I'm getting the following error, when I try to apply the filter:

Debug info: ERROR: column "u.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT u.* FROM mdl_user u WHERE (u.deleted = 0 and u.id <> ...
^
SELECT u.* FROM mdl_user u WHERE (u.deleted = 0 and u.id <> 1) HAVING department = $1
[array (
0 => 'Teachers',
)]

**Comment by rhell4** [comment]
Hi, I've just created a pull request which should fix this issue.

**Comment by cnw-co** [comment]
Thank you! The new release works with PostgreSQL too.
