### ISSUE TITLE
Postgresql doesn't accept field aliases in Having clauses

### ISSUE THREAD

**Issue by adamtppaw** [cnw-co/moodle-local_cnw_smartcohort#4]
Hi , we experience an error on Postgresql 12.

Debug info: ERROR: column "profile_field_typuzytkownika" doesn't exists
LINE 1: ...user u WHERE (u.deleted = 0 and u.id <> 1) HAVING profile_fi...
^
SELECT u.*, (SELECT UID.data FROM mdl_user_info_field UIF, mdl_user_info_data UID WHERE UID.fieldid = UIF.id AND UIF.shortname = 'typuzytkownika' AND UID.userid = u.id) as profile_field_typuzytkownika FROM mdl_user u WHERE (u.deleted = 0 and u.id <> 1) HAVING profile_field_typuzytkownika = $1 AND department = $2
[array (
0 => 'wykladowca',
1 => 'POZ',
)]
Error code: dmlreadexception

Adam

**Comment by cnw-co** [comment]
Thank you! The new release works with PostgreSQL too.
