### ISSUE TITLE
issue with filtering

### ISSUE THREAD

**Issue by Lysa14** [cnw-co/moodle-local_cnw_smartcohort#5]
When deleting a previously created filter, the deletion operation remains frozen indefinitely.
Additionally, the email filter does not work. It is possible to create filters in the Smartcohort plugin as follows: if the value of the "Email Address" field is equal to, different from, begins with, or ends with a certain value.

I am trying to exclude ALL users who do not have an email address ending in "@my-organization.com" using a filter to populate a cohort named "External Users." However, if I use the "different from" filter (than "@my-organization.com"), it considers all Moodle emails, as they are all different from "@my-organization.com". This results in all Moodle users being added to the cohort, which is not the desired outcome.

If we look at how Moodle's "native" filters work (users -> batch actions on users), it is possible to achieve the desired result by using the "does not contain" filter with "@my-organization.com". I do get the list of external users that I am trying to automatically place in a cohort.

This filter is unusable to properly filter email addresses. It should behave like Moodle's filter.

**Comment by Lysa14** [comment]
The modifications made to the email filter code have been successfully tested on version 3.9 and the latest version of Moodle 4.2.

**Comment by cnw-co** [comment]
Thank you!
In the new relase the filtering works like the native Moodle user filtering.
